services:
  web:
    build: .
    # This allows PHP to use 'localhost' to find the DB
    network_mode: "service:db" 
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:18
    restart: always
    ports:
      - "8080:80"   # Website: http://localhost:8080
      - "5432:5432" # Database: localhost:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: