version: '3.8'

services:
  db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
      - "8080:80" 
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      # CHANGE: Remove the /data suffix as required by Postgres 18
      - postgres_data:/var/lib/postgresql

  web:
    build: .
    network_mode: "service:db"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: